export const RESERVATION_LIST_REQUEST = 'RESERVATION_LIST_REQUEST';
export const RESERVATION_LIST_SUCCESS = 'RESERVATION_LIST_SUCCESS';
export const RESERVATION_LIST_FAIL = 'RESERVATION_LIST_FAIL';

export const RESERVATION_DETAILS_REQUEST = 'RESERVATION_DETAILS_REQUEST';
export const RESERVATION_DETAILS_SUCCESS = 'RESERVATION_DETAILS_SUCCESS';
export const RESERVATION_DETAILS_FAIL = 'RESERVATION_DETAILS_FAIL';

export const RESERVATION_SAVE_REQUEST = 'RESERVATION_SAVE_REQUEST';
export const RESERVATION_SAVE_SUCCESS = 'RESERVATION_SAVE_SUCCESS';
export const RESERVATION_SAVE_FAIL = 'RESERVATION_SAVE_FAIL';

export const RESERVATION_UPDATE_REQUEST = 'RESERVATION_UPDATE_REQUEST';
export const RESERVATION_UPDATE_SUCCESS = 'RESERVATION_UPDATE_SUCCESS';
export const RESERVATION_UPDATE_FAIL = 'RESERVATION_UPDATE_FAIL';

export const RESERVATION_DELETE_REQUEST = 'RESERVATION_DELETE_REQUEST';
export const RESERVATION_DELETE_SUCCESS = 'RESERVATION_DELETE_SUCCESS';
export const RESERVATION_DELETE_FAIL = 'RESERVATION_DELETE_FAIL';